# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    # Identify invalid files
    - id: check-ast
    - id: check-yaml
    - id: check-json
    - id: check-toml
    # git checks
    - id: check-merge-conflict
    - id: check-added-large-files
      exclude: tests/media/.+
    - id: detect-private-key
    - id: check-case-conflict
    # Python checks
    - id: check-docstring-first
    - id: debug-statements
    - id: requirements-txt-fixer
    - id: fix-encoding-pragma
    - id: fix-byte-order-marker
    # General quality checks
    - id: mixed-line-ending
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-executables-have-shebangs
    - id: end-of-file-fixer
  # Add at same level as the first pre-commit-hooks repo
  - repo: https://github.com/psf/black
    rev: e3000ace2fd1fcb1c181bb7a8285f1f976bcbdc7  # frozen: 21.7b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: dcd740bc0ebaf2b3d43e59a0060d157c97de13f3  # frozen: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
          - flake8-typing-imports==1.10.1
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: fd5ba70665a37ec301a1f714ed09336048b3be63  # frozen: 5.9.3
    hooks:
      - id: isort
        name: isort (python)
        args: [ "--profile", "black", "--filter-files" ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 44afb68a9695d04030edc5cdc5a4fc4f17e4f9e2
    hooks:
      - id: mypy
        args: [ --ignore-missing-imports ]
